# Generated by Django 3.1.3 on 2020-11-07 13:00

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201105_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post/default.jpg', upload_to=blog.models.upload_to, verbose_name='Image'),
        ),
    ]
